(ns chapter-1.exercise-1-15)

;; The sine of an angle (specified in radians) can be computed
;; by making use of the approximation sin x if x is suﬃciently small,
;; and the trigonometric identity sin(x) = 3 * sin(x / 3) + 4 * (sin(x / 3)) ^ 3
;; to reduce the size of the argument of sin. (For purposes of
;; this exercise an angle is considered “suﬃciently small” if its
;; magnitude is not greater than 0.1 radians.) ese ideas are
;; incorporated in the following procedures:
(defn cube [x] (* x x x))
(defn p [x] (- (* 3 x) (* 4 (cube x))))
(defn sine [angle]
  (if (not (> (abs angle) 0.1))
    angle
    (p (sine (/ angle 3.0)))))

;; How many times is the procedure p applied when (sine 12.15) is evaluated?
(sine 12.15)
;; we need to find x so 
;; x / (3^n) ≤ 0.1)
;; 12.15 / (3^n) ≤ 0.1
;; 12.15 ≤ 0.1 × 3^n 
;; 121.5 ≤ 3^n
;; log₃(121.5) ≤ n
;; 4.37... ≤ n
;; n = 5
(p (sine (/ 12.15 3.0)))
(p (sine 4.05))
(p (p (sine (/ 4.05 3.0))))
(p (p (sine 1.35)))
(p (p (p (sine (/ 1.35 3.0)))))
(p (p (p (sine 0.45))))
(p (p (p (p (sine (/ 0.45 3.0))))))
(p (p (p (p (sine 0.15)))))
(p (p (p (p (p (sine (/ 0.15 3.0)))))))
(p (p (p (p (p (sine 0.05))))))

;; What is the order of growth in space and number of steps (as a function of a)
;; used by the process generated by the sine procedure when (sine a) is evaluated?

;; Time complexity
;; x / (3^n) ≤ 0.1
;; n ≥ log₃(10x) => Θ(log(x))

;; Space complexity
;; We make log₃(x) calls => Θ(log(x))
